application: grapheditor
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: html/index.html
  upload: html/index\.html

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /html/(.*\.(html$))
  static_files: html/\1
  upload: html/(.*\.(html$))

- url: /js/(.*\.(js$))
  static_files: js/\1
  upload: js/(.*\.(js$))

- url: /css/(.*\.(css$))
  static_files: css/\1
  upload: css/(.*\.(css$))
